env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:typescript-sort-keys/recommended
  - plugin:prettier/recommended
  - prettier
  # - prettier/@typescript-eslint
  # - prettier/react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - import
  - typescript-sort-keys
  - sort-destructure-keys
  - react
  - react-hooks
  - '@typescript-eslint'
  - sort-keys-fix
settings:
  react:
    version: detect
rules:
  react/prop-types: 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  "@typescript-eslint/ban-ts-comment": "off"
  '@typescript-eslint/no-unused-vars':
    - warn
    - ignoreRestSiblings: true
  react-hooks/exhaustive-deps: warn
  sort-destructure-keys/sort-destructure-keys:
    - error
    - caseSensitive: true
  import/no-default-export: error
  # poniżej auto-fixy
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  sort-keys-fix/sort-keys-fix: error
  react-hooks/rules-of-hooks: error
  newline-after-var: warn
  newline-before-return: warn
  no-else-return: warn
  eol-last: warn
  sort-vars: warn
  prefer-template: warn
  react/jsx-sort-props: error
