"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function AuditFromJSON(json) {
    return AuditFromJSONTyped(json, false);
}
exports.AuditFromJSON = AuditFromJSON;
function AuditFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'dataSet': !runtime_1.exists(json, 'dataSet') ? undefined : _1.AuditDataSetFromJSON(json['dataSet']),
        'header': !runtime_1.exists(json, 'header') ? undefined : json['header'],
        'message': !runtime_1.exists(json, 'message') ? undefined : json['message'],
        'initiator': !runtime_1.exists(json, 'initiator') ? undefined : json['initiator'],
        'date': !runtime_1.exists(json, 'date') ? undefined : (new Date(json['date'])),
    };
}
exports.AuditFromJSONTyped = AuditFromJSONTyped;
function AuditToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'dataSet': _1.AuditDataSetToJSON(value.dataSet),
        'header': value.header,
        'message': value.message,
        'initiator': value.initiator,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
    };
}
exports.AuditToJSON = AuditToJSON;
