"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function AuditsResponseFromJSON(json) {
    return AuditsResponseFromJSONTyped(json, false);
}
exports.AuditsResponseFromJSON = AuditsResponseFromJSON;
function AuditsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'pageInfo': !runtime_1.exists(json, 'pageInfo') ? undefined : _1.PageInfoFromJSON(json['pageInfo']),
        'audits': !runtime_1.exists(json, 'audits') ? undefined : (json['audits'].map(_1.AuditFromJSON)),
    };
}
exports.AuditsResponseFromJSONTyped = AuditsResponseFromJSONTyped;
function AuditsResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'pageInfo': _1.PageInfoToJSON(value.pageInfo),
        'audits': value.audits === undefined ? undefined : (value.audits.map(_1.AuditToJSON)),
    };
}
exports.AuditsResponseToJSON = AuditsResponseToJSON;
