/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDataSet } from './';
/**
 *
 * @export
 * @interface Audit
 */
export interface Audit {
    /**
     *
     * @type {AuditDataSet}
     * @memberof Audit
     */
    dataSet?: AuditDataSet;
    /**
     *
     * @type {string}
     * @memberof Audit
     */
    header?: string;
    /**
     *
     * @type {string}
     * @memberof Audit
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof Audit
     */
    initiator?: string;
    /**
     *
     * @type {Date}
     * @memberof Audit
     */
    date?: Date;
}
export declare function AuditFromJSON(json: any): Audit;
export declare function AuditFromJSONTyped(json: any, ignoreDiscriminator: boolean): Audit;
export declare function AuditToJSON(value?: Audit | null): any;
