/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum AuditDataSet {
    CUSTOMER = "CUSTOMER",
    PRODUCT = "PRODUCT"
}
export declare function AuditDataSetFromJSON(json: any): AuditDataSet;
export declare function AuditDataSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditDataSet;
export declare function AuditDataSetToJSON(value?: AuditDataSet | null): any;
