"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var AuditDataSet;
(function (AuditDataSet) {
    AuditDataSet["CUSTOMER"] = "CUSTOMER";
    AuditDataSet["PRODUCT"] = "PRODUCT";
})(AuditDataSet = exports.AuditDataSet || (exports.AuditDataSet = {}));
function AuditDataSetFromJSON(json) {
    return AuditDataSetFromJSONTyped(json, false);
}
exports.AuditDataSetFromJSON = AuditDataSetFromJSON;
function AuditDataSetFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.AuditDataSetFromJSONTyped = AuditDataSetFromJSONTyped;
function AuditDataSetToJSON(value) {
    return value;
}
exports.AuditDataSetToJSON = AuditDataSetToJSON;
