/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './';
/**
 *
 * @export
 * @interface AuthenticatedUserResponse
 */
export interface AuthenticatedUserResponse {
    /**
     *
     * @type {User}
     * @memberof AuthenticatedUserResponse
     */
    user?: User;
}
export declare function AuthenticatedUserResponseFromJSON(json: any): AuthenticatedUserResponse;
export declare function AuthenticatedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedUserResponse;
export declare function AuthenticatedUserResponseToJSON(value?: AuthenticatedUserResponse | null): any;
