/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum BooleanValue {
    TRUE = "TRUE",
    FALSE = "FALSE"
}
export declare function BooleanValueFromJSON(json: any): BooleanValue;
export declare function BooleanValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanValue;
export declare function BooleanValueToJSON(value?: BooleanValue | null): any;
