/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerNativeStatus, CustomerState, CustomerType, RejectionReason, SourceSystem } from './';
/**
 *
 * @export
 * @interface CustomerDetails
 */
export interface CustomerDetails {
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    erpId?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    nativeId?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    companyName?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    streetAddress?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    postalCode?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    countryCode?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    city?: string;
    /**
     *
     * @type {CustomerType}
     * @memberof CustomerDetails
     */
    type?: CustomerType;
    /**
     *
     * @type {CustomerNativeStatus}
     * @memberof CustomerDetails
     */
    nativeStatus?: CustomerNativeStatus;
    /**
     *
     * @type {CustomerState}
     * @memberof CustomerDetails
     */
    state?: CustomerState;
    /**
     *
     * @type {Date}
     * @memberof CustomerDetails
     */
    nativeCreatedDate?: Date;
    /**
     *
     * @type {SourceSystem}
     * @memberof CustomerDetails
     */
    sourceSystem?: SourceSystem;
    /**
     *
     * @type {RejectionReason}
     * @memberof CustomerDetails
     */
    rejectionReason?: RejectionReason;
    /**
     *
     * @type {string}
     * @memberof CustomerDetails
     */
    freeText?: string;
}
export declare function CustomerDetailsFromJSON(json: any): CustomerDetails;
export declare function CustomerDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDetails;
export declare function CustomerDetailsToJSON(value?: CustomerDetails | null): any;
