/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Language, SearchCustomersBy, SortCustomersBy, SortDirection } from './';
/**
 *
 * @export
 * @interface CustomersRequest
 */
export interface CustomersRequest {
    /**
     *
     * @type {number}
     * @memberof CustomersRequest
     */
    pageSize?: number;
    /**
     *
     * @type {number}
     * @memberof CustomersRequest
     */
    pageNumber?: number;
    /**
     *
     * @type {SortCustomersBy}
     * @memberof CustomersRequest
     */
    sortBy: SortCustomersBy;
    /**
     *
     * @type {SortDirection}
     * @memberof CustomersRequest
     */
    sortDirection: SortDirection;
    /**
     *
     * @type {Array<SearchCustomersBy>}
     * @memberof CustomersRequest
     */
    filters?: Array<SearchCustomersBy>;
    /**
     *
     * @type {Language}
     * @memberof CustomersRequest
     */
    language: Language;
}
export declare function CustomersRequestFromJSON(json: any): CustomersRequest;
export declare function CustomersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersRequest;
export declare function CustomersRequestToJSON(value?: CustomersRequest | null): any;
