/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerContactDetails, CustomerType } from './';
/**
 *
 * @export
 * @interface CustomerLookup
 */
export interface CustomerLookup {
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    erpId?: string;
    /**
     *
     * @type {CustomerType}
     * @memberof CustomerLookup
     */
    type?: CustomerType;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    name1?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    name2?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    name3?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    name4?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    streetAddress?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    postalCode?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    countryCode?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerLookup
     */
    city?: string;
    /**
     *
     * @type {CustomerContactDetails}
     * @memberof CustomerLookup
     */
    contactDetails?: CustomerContactDetails;
}
export declare function CustomerLookupFromJSON(json: any): CustomerLookup;
export declare function CustomerLookupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerLookup;
export declare function CustomerLookupToJSON(value?: CustomerLookup | null): any;
