"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function CustomerDetailsFromJSON(json) {
    return CustomerDetailsFromJSONTyped(json, false);
}
exports.CustomerDetailsFromJSON = CustomerDetailsFromJSON;
function CustomerDetailsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'erpId': !runtime_1.exists(json, 'erpId') ? undefined : json['erpId'],
        'firstName': !runtime_1.exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !runtime_1.exists(json, 'lastName') ? undefined : json['lastName'],
        'nativeId': !runtime_1.exists(json, 'nativeId') ? undefined : json['nativeId'],
        'title': !runtime_1.exists(json, 'title') ? undefined : json['title'],
        'companyName': !runtime_1.exists(json, 'companyName') ? undefined : json['companyName'],
        'streetAddress': !runtime_1.exists(json, 'streetAddress') ? undefined : json['streetAddress'],
        'postalCode': !runtime_1.exists(json, 'postalCode') ? undefined : json['postalCode'],
        'countryCode': !runtime_1.exists(json, 'countryCode') ? undefined : json['countryCode'],
        'city': !runtime_1.exists(json, 'city') ? undefined : json['city'],
        'type': !runtime_1.exists(json, 'type') ? undefined : _1.CustomerTypeFromJSON(json['type']),
        'nativeStatus': !runtime_1.exists(json, 'nativeStatus') ? undefined : _1.CustomerNativeStatusFromJSON(json['nativeStatus']),
        'state': !runtime_1.exists(json, 'state') ? undefined : _1.CustomerStateFromJSON(json['state']),
        'nativeCreatedDate': !runtime_1.exists(json, 'nativeCreatedDate') ? undefined : (new Date(json['nativeCreatedDate'])),
        'sourceSystem': !runtime_1.exists(json, 'sourceSystem') ? undefined : _1.SourceSystemFromJSON(json['sourceSystem']),
        'rejectionReason': !runtime_1.exists(json, 'rejectionReason') ? undefined : _1.RejectionReasonFromJSON(json['rejectionReason']),
        'freeText': !runtime_1.exists(json, 'freeText') ? undefined : json['freeText'],
    };
}
exports.CustomerDetailsFromJSONTyped = CustomerDetailsFromJSONTyped;
function CustomerDetailsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'erpId': value.erpId,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'nativeId': value.nativeId,
        'title': value.title,
        'companyName': value.companyName,
        'streetAddress': value.streetAddress,
        'postalCode': value.postalCode,
        'countryCode': value.countryCode,
        'city': value.city,
        'type': _1.CustomerTypeToJSON(value.type),
        'nativeStatus': _1.CustomerNativeStatusToJSON(value.nativeStatus),
        'state': _1.CustomerStateToJSON(value.state),
        'nativeCreatedDate': value.nativeCreatedDate === undefined ? undefined : (value.nativeCreatedDate.toISOString()),
        'sourceSystem': _1.SourceSystemToJSON(value.sourceSystem),
        'rejectionReason': _1.RejectionReasonToJSON(value.rejectionReason),
        'freeText': value.freeText,
    };
}
exports.CustomerDetailsToJSON = CustomerDetailsToJSON;
