/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerDetails } from './';
/**
 *
 * @export
 * @interface CustomerDetailsResponse
 */
export interface CustomerDetailsResponse {
    /**
     *
     * @type {CustomerDetails}
     * @memberof CustomerDetailsResponse
     */
    customer?: CustomerDetails;
}
export declare function CustomerDetailsResponseFromJSON(json: any): CustomerDetailsResponse;
export declare function CustomerDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDetailsResponse;
export declare function CustomerDetailsResponseToJSON(value?: CustomerDetailsResponse | null): any;
