"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var CustomerType;
(function (CustomerType) {
    CustomerType["DELIVERY"] = "DELIVERY";
    CustomerType["VETPRACTICE"] = "VET_PRACTICE";
    CustomerType["OTHER"] = "OTHER";
})(CustomerType = exports.CustomerType || (exports.CustomerType = {}));
function CustomerTypeFromJSON(json) {
    return CustomerTypeFromJSONTyped(json, false);
}
exports.CustomerTypeFromJSON = CustomerTypeFromJSON;
function CustomerTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.CustomerTypeFromJSONTyped = CustomerTypeFromJSONTyped;
function CustomerTypeToJSON(value) {
    return value;
}
exports.CustomerTypeToJSON = CustomerTypeToJSON;
