"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function CustomerLookupResponseFromJSON(json) {
    return CustomerLookupResponseFromJSONTyped(json, false);
}
exports.CustomerLookupResponseFromJSON = CustomerLookupResponseFromJSON;
function CustomerLookupResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'customerLookup': !runtime_1.exists(json, 'customerLookup') ? undefined : _1.CustomerLookupFromJSON(json['customerLookup']),
    };
}
exports.CustomerLookupResponseFromJSONTyped = CustomerLookupResponseFromJSONTyped;
function CustomerLookupResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'customerLookup': _1.CustomerLookupToJSON(value.customerLookup),
    };
}
exports.CustomerLookupResponseToJSON = CustomerLookupResponseToJSON;
