"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function CustomerFromJSON(json) {
    return CustomerFromJSONTyped(json, false);
}
exports.CustomerFromJSON = CustomerFromJSON;
function CustomerFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'erpId': !runtime_1.exists(json, 'erpId') ? undefined : json['erpId'],
        'type': !runtime_1.exists(json, 'type') ? undefined : _1.CustomerTypeFromJSON(json['type']),
        'nativeStatus': !runtime_1.exists(json, 'nativeStatus') ? undefined : _1.CustomerNativeStatusFromJSON(json['nativeStatus']),
        'companyName': !runtime_1.exists(json, 'companyName') ? undefined : json['companyName'],
        'address': !runtime_1.exists(json, 'address') ? undefined : json['address'],
        'state': !runtime_1.exists(json, 'state') ? undefined : _1.CustomerStateFromJSON(json['state']),
        'nativeCreatedDate': !runtime_1.exists(json, 'nativeCreatedDate') ? undefined : (new Date(json['nativeCreatedDate'])),
        'sourceSystem': !runtime_1.exists(json, 'sourceSystem') ? undefined : _1.SourceSystemFromJSON(json['sourceSystem']),
        'rejectionReason': !runtime_1.exists(json, 'rejectionReason') ? undefined : _1.RejectionReasonFromJSON(json['rejectionReason']),
    };
}
exports.CustomerFromJSONTyped = CustomerFromJSONTyped;
function CustomerToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'erpId': value.erpId,
        'type': _1.CustomerTypeToJSON(value.type),
        'nativeStatus': _1.CustomerNativeStatusToJSON(value.nativeStatus),
        'companyName': value.companyName,
        'address': value.address,
        'state': _1.CustomerStateToJSON(value.state),
        'nativeCreatedDate': value.nativeCreatedDate === undefined ? undefined : (value.nativeCreatedDate.toISOString()),
        'sourceSystem': _1.SourceSystemToJSON(value.sourceSystem),
        'rejectionReason': _1.RejectionReasonToJSON(value.rejectionReason),
    };
}
exports.CustomerToJSON = CustomerToJSON;
