/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum CustomerState {
    ACTIVE = "ACTIVE",
    DELETED = "DELETED"
}
export declare function CustomerStateFromJSON(json: any): CustomerState;
export declare function CustomerStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerState;
export declare function CustomerStateToJSON(value?: CustomerState | null): any;
