"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function CustomerLookupFromJSON(json) {
    return CustomerLookupFromJSONTyped(json, false);
}
exports.CustomerLookupFromJSON = CustomerLookupFromJSON;
function CustomerLookupFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'erpId': !runtime_1.exists(json, 'erpId') ? undefined : json['erpId'],
        'type': !runtime_1.exists(json, 'type') ? undefined : _1.CustomerTypeFromJSON(json['type']),
        'name1': !runtime_1.exists(json, 'name1') ? undefined : json['name1'],
        'name2': !runtime_1.exists(json, 'name2') ? undefined : json['name2'],
        'name3': !runtime_1.exists(json, 'name3') ? undefined : json['name3'],
        'name4': !runtime_1.exists(json, 'name4') ? undefined : json['name4'],
        'title': !runtime_1.exists(json, 'title') ? undefined : json['title'],
        'streetAddress': !runtime_1.exists(json, 'streetAddress') ? undefined : json['streetAddress'],
        'postalCode': !runtime_1.exists(json, 'postalCode') ? undefined : json['postalCode'],
        'countryCode': !runtime_1.exists(json, 'countryCode') ? undefined : json['countryCode'],
        'city': !runtime_1.exists(json, 'city') ? undefined : json['city'],
        'contactDetails': !runtime_1.exists(json, 'contactDetails') ? undefined : _1.CustomerContactDetailsFromJSON(json['contactDetails']),
    };
}
exports.CustomerLookupFromJSONTyped = CustomerLookupFromJSONTyped;
function CustomerLookupToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'erpId': value.erpId,
        'type': _1.CustomerTypeToJSON(value.type),
        'name1': value.name1,
        'name2': value.name2,
        'name3': value.name3,
        'name4': value.name4,
        'title': value.title,
        'streetAddress': value.streetAddress,
        'postalCode': value.postalCode,
        'countryCode': value.countryCode,
        'city': value.city,
        'contactDetails': _1.CustomerContactDetailsToJSON(value.contactDetails),
    };
}
exports.CustomerLookupToJSON = CustomerLookupToJSON;
