/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum CustomerNativeStatus {
    INREVIEW = "IN_REVIEW",
    VALIDATED = "VALIDATED",
    BLOCKED = "BLOCKED"
}
export declare function CustomerNativeStatusFromJSON(json: any): CustomerNativeStatus;
export declare function CustomerNativeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerNativeStatus;
export declare function CustomerNativeStatusToJSON(value?: CustomerNativeStatus | null): any;
