/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerPartial } from './';
/**
 *
 * @export
 * @interface CustomerPartialRequest
 */
export interface CustomerPartialRequest {
    /**
     *
     * @type {CustomerPartial}
     * @memberof CustomerPartialRequest
     */
    customerPartial: CustomerPartial;
}
export declare function CustomerPartialRequestFromJSON(json: any): CustomerPartialRequest;
export declare function CustomerPartialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPartialRequest;
export declare function CustomerPartialRequestToJSON(value?: CustomerPartialRequest | null): any;
