"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function CustomersResponseFromJSON(json) {
    return CustomersResponseFromJSONTyped(json, false);
}
exports.CustomersResponseFromJSON = CustomersResponseFromJSON;
function CustomersResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'pageInfo': !runtime_1.exists(json, 'pageInfo') ? undefined : _1.PageInfoFromJSON(json['pageInfo']),
        'customers': !runtime_1.exists(json, 'customers') ? undefined : (json['customers'].map(_1.CustomerFromJSON)),
        'localizedCustomerStates': !runtime_1.exists(json, 'localizedCustomerStates') ? undefined : (json['localizedCustomerStates'].map(_1.LocalizedCustomerStateFromJSON)),
        'localizedCustomerNativeStatuses': !runtime_1.exists(json, 'localizedCustomerNativeStatuses') ? undefined : (json['localizedCustomerNativeStatuses'].map(_1.LocalizedCustomerNativeStatusFromJSON)),
        'localizedCustomerTypes': !runtime_1.exists(json, 'localizedCustomerTypes') ? undefined : (json['localizedCustomerTypes'].map(_1.LocalizedCustomerTypeFromJSON)),
        'localizedRejectionReasons': !runtime_1.exists(json, 'localizedRejectionReasons') ? undefined : (json['localizedRejectionReasons'].map(_1.LocalizedRejectionReasonFromJSON)),
    };
}
exports.CustomersResponseFromJSONTyped = CustomersResponseFromJSONTyped;
function CustomersResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'pageInfo': _1.PageInfoToJSON(value.pageInfo),
        'customers': value.customers === undefined ? undefined : (value.customers.map(_1.CustomerToJSON)),
        'localizedCustomerStates': value.localizedCustomerStates === undefined ? undefined : (value.localizedCustomerStates.map(_1.LocalizedCustomerStateToJSON)),
        'localizedCustomerNativeStatuses': value.localizedCustomerNativeStatuses === undefined ? undefined : (value.localizedCustomerNativeStatuses.map(_1.LocalizedCustomerNativeStatusToJSON)),
        'localizedCustomerTypes': value.localizedCustomerTypes === undefined ? undefined : (value.localizedCustomerTypes.map(_1.LocalizedCustomerTypeToJSON)),
        'localizedRejectionReasons': value.localizedRejectionReasons === undefined ? undefined : (value.localizedRejectionReasons.map(_1.LocalizedRejectionReasonToJSON)),
    };
}
exports.CustomersResponseToJSON = CustomersResponseToJSON;
