/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer, LocalizedCustomerNativeStatus, LocalizedCustomerState, LocalizedCustomerType, LocalizedRejectionReason, PageInfo } from './';
/**
 *
 * @export
 * @interface CustomersResponse
 */
export interface CustomersResponse {
    /**
     *
     * @type {PageInfo}
     * @memberof CustomersResponse
     */
    pageInfo?: PageInfo;
    /**
     *
     * @type {Array<Customer>}
     * @memberof CustomersResponse
     */
    customers?: Array<Customer>;
    /**
     *
     * @type {Array<LocalizedCustomerState>}
     * @memberof CustomersResponse
     */
    localizedCustomerStates?: Array<LocalizedCustomerState>;
    /**
     *
     * @type {Array<LocalizedCustomerNativeStatus>}
     * @memberof CustomersResponse
     */
    localizedCustomerNativeStatuses?: Array<LocalizedCustomerNativeStatus>;
    /**
     *
     * @type {Array<LocalizedCustomerType>}
     * @memberof CustomersResponse
     */
    localizedCustomerTypes?: Array<LocalizedCustomerType>;
    /**
     *
     * @type {Array<LocalizedRejectionReason>}
     * @memberof CustomersResponse
     */
    localizedRejectionReasons?: Array<LocalizedRejectionReason>;
}
export declare function CustomersResponseFromJSON(json: any): CustomersResponse;
export declare function CustomersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersResponse;
export declare function CustomersResponseToJSON(value?: CustomersResponse | null): any;
