/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CustomerContactDetails
 */
export interface CustomerContactDetails {
    /**
     *
     * @type {string}
     * @memberof CustomerContactDetails
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerContactDetails
     */
    phoneNumber?: string;
    /**
     *
     * @type {string}
     * @memberof CustomerContactDetails
     */
    searchTerms?: string;
}
export declare function CustomerContactDetailsFromJSON(json: any): CustomerContactDetails;
export declare function CustomerContactDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerContactDetails;
export declare function CustomerContactDetailsToJSON(value?: CustomerContactDetails | null): any;
