"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var CustomerState;
(function (CustomerState) {
    CustomerState["ACTIVE"] = "ACTIVE";
    CustomerState["DELETED"] = "DELETED";
})(CustomerState = exports.CustomerState || (exports.CustomerState = {}));
function CustomerStateFromJSON(json) {
    return CustomerStateFromJSONTyped(json, false);
}
exports.CustomerStateFromJSON = CustomerStateFromJSON;
function CustomerStateFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.CustomerStateFromJSONTyped = CustomerStateFromJSONTyped;
function CustomerStateToJSON(value) {
    return value;
}
exports.CustomerStateToJSON = CustomerStateToJSON;
