/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalizedBooleanValue, LocalizedCustomerNativeStatus, LocalizedCustomerState, LocalizedCustomerType, LocalizedErrorCode, LocalizedProductAvailability, LocalizedRejectionReason } from './';
/**
 *
 * @export
 * @interface DictionariesResponse
 */
export interface DictionariesResponse {
    /**
     *
     * @type {Array<LocalizedCustomerState>}
     * @memberof DictionariesResponse
     */
    localizedCustomerStates?: Array<LocalizedCustomerState>;
    /**
     *
     * @type {Array<LocalizedCustomerNativeStatus>}
     * @memberof DictionariesResponse
     */
    localizedCustomerNativeStatuses?: Array<LocalizedCustomerNativeStatus>;
    /**
     *
     * @type {Array<LocalizedCustomerType>}
     * @memberof DictionariesResponse
     */
    localizedCustomerTypes?: Array<LocalizedCustomerType>;
    /**
     *
     * @type {Array<LocalizedRejectionReason>}
     * @memberof DictionariesResponse
     */
    localizedRejectionReasons?: Array<LocalizedRejectionReason>;
    /**
     *
     * @type {Array<LocalizedProductAvailability>}
     * @memberof DictionariesResponse
     */
    localizedProductAvailabilities?: Array<LocalizedProductAvailability>;
    /**
     *
     * @type {Array<LocalizedBooleanValue>}
     * @memberof DictionariesResponse
     */
    localizedBooleanValues?: Array<LocalizedBooleanValue>;
    /**
     *
     * @type {Array<LocalizedErrorCode>}
     * @memberof DictionariesResponse
     */
    localizedErrorCodes?: Array<LocalizedErrorCode>;
}
export declare function DictionariesResponseFromJSON(json: any): DictionariesResponse;
export declare function DictionariesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DictionariesResponse;
export declare function DictionariesResponseToJSON(value?: DictionariesResponse | null): any;
