"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function DictionariesResponseFromJSON(json) {
    return DictionariesResponseFromJSONTyped(json, false);
}
exports.DictionariesResponseFromJSON = DictionariesResponseFromJSON;
function DictionariesResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'localizedCustomerStates': !runtime_1.exists(json, 'localizedCustomerStates') ? undefined : (json['localizedCustomerStates'].map(_1.LocalizedCustomerStateFromJSON)),
        'localizedCustomerNativeStatuses': !runtime_1.exists(json, 'localizedCustomerNativeStatuses') ? undefined : (json['localizedCustomerNativeStatuses'].map(_1.LocalizedCustomerNativeStatusFromJSON)),
        'localizedCustomerTypes': !runtime_1.exists(json, 'localizedCustomerTypes') ? undefined : (json['localizedCustomerTypes'].map(_1.LocalizedCustomerTypeFromJSON)),
        'localizedRejectionReasons': !runtime_1.exists(json, 'localizedRejectionReasons') ? undefined : (json['localizedRejectionReasons'].map(_1.LocalizedRejectionReasonFromJSON)),
        'localizedProductAvailabilities': !runtime_1.exists(json, 'localizedProductAvailabilities') ? undefined : (json['localizedProductAvailabilities'].map(_1.LocalizedProductAvailabilityFromJSON)),
        'localizedBooleanValues': !runtime_1.exists(json, 'localizedBooleanValues') ? undefined : (json['localizedBooleanValues'].map(_1.LocalizedBooleanValueFromJSON)),
        'localizedErrorCodes': !runtime_1.exists(json, 'localizedErrorCodes') ? undefined : (json['localizedErrorCodes'].map(_1.LocalizedErrorCodeFromJSON)),
    };
}
exports.DictionariesResponseFromJSONTyped = DictionariesResponseFromJSONTyped;
function DictionariesResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'localizedCustomerStates': value.localizedCustomerStates === undefined ? undefined : (value.localizedCustomerStates.map(_1.LocalizedCustomerStateToJSON)),
        'localizedCustomerNativeStatuses': value.localizedCustomerNativeStatuses === undefined ? undefined : (value.localizedCustomerNativeStatuses.map(_1.LocalizedCustomerNativeStatusToJSON)),
        'localizedCustomerTypes': value.localizedCustomerTypes === undefined ? undefined : (value.localizedCustomerTypes.map(_1.LocalizedCustomerTypeToJSON)),
        'localizedRejectionReasons': value.localizedRejectionReasons === undefined ? undefined : (value.localizedRejectionReasons.map(_1.LocalizedRejectionReasonToJSON)),
        'localizedProductAvailabilities': value.localizedProductAvailabilities === undefined ? undefined : (value.localizedProductAvailabilities.map(_1.LocalizedProductAvailabilityToJSON)),
        'localizedBooleanValues': value.localizedBooleanValues === undefined ? undefined : (value.localizedBooleanValues.map(_1.LocalizedBooleanValueToJSON)),
        'localizedErrorCodes': value.localizedErrorCodes === undefined ? undefined : (value.localizedErrorCodes.map(_1.LocalizedErrorCodeToJSON)),
    };
}
exports.DictionariesResponseToJSON = DictionariesResponseToJSON;
