"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var ErrorCode;
(function (ErrorCode) {
    ErrorCode["INTERNALSERVERERROR"] = "INTERNAL_SERVER_ERROR";
    ErrorCode["BADREQUEST"] = "BAD_REQUEST";
    ErrorCode["FORBIDDEN"] = "FORBIDDEN";
    ErrorCode["NOTFOUND"] = "NOT_FOUND";
    ErrorCode["CONFLICT"] = "CONFLICT";
    ErrorCode["INCORRECTFREETEXTVALUE"] = "INCORRECT_FREE_TEXT_VALUE";
})(ErrorCode = exports.ErrorCode || (exports.ErrorCode = {}));
function ErrorCodeFromJSON(json) {
    return ErrorCodeFromJSONTyped(json, false);
}
exports.ErrorCodeFromJSON = ErrorCodeFromJSON;
function ErrorCodeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.ErrorCodeFromJSONTyped = ErrorCodeFromJSONTyped;
function ErrorCodeToJSON(value) {
    return value;
}
exports.ErrorCodeToJSON = ErrorCodeToJSON;
