/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum ErrorCode {
    INTERNALSERVERERROR = "INTERNAL_SERVER_ERROR",
    BADREQUEST = "BAD_REQUEST",
    FORBIDDEN = "FORBIDDEN",
    NOTFOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INCORRECTFREETEXTVALUE = "INCORRECT_FREE_TEXT_VALUE"
}
export declare function ErrorCodeFromJSON(json: any): ErrorCode;
export declare function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode;
export declare function ErrorCodeToJSON(value?: ErrorCode | null): any;
