/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum Language {
    DE = "DE"
}
export declare function LanguageFromJSON(json: any): Language;
export declare function LanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Language;
export declare function LanguageToJSON(value?: Language | null): any;
