"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var Language;
(function (Language) {
    Language["DE"] = "DE";
})(Language = exports.Language || (exports.Language = {}));
function LanguageFromJSON(json) {
    return LanguageFromJSONTyped(json, false);
}
exports.LanguageFromJSON = LanguageFromJSON;
function LanguageFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.LanguageFromJSONTyped = LanguageFromJSONTyped;
function LanguageToJSON(value) {
    return value;
}
exports.LanguageToJSON = LanguageToJSON;
