/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerType } from './';
/**
 *
 * @export
 * @interface LocalizedCustomerType
 */
export interface LocalizedCustomerType {
    /**
     *
     * @type {CustomerType}
     * @memberof LocalizedCustomerType
     */
    type?: CustomerType;
    /**
     *
     * @type {string}
     * @memberof LocalizedCustomerType
     */
    localizedType?: string;
}
export declare function LocalizedCustomerTypeFromJSON(json: any): LocalizedCustomerType;
export declare function LocalizedCustomerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedCustomerType;
export declare function LocalizedCustomerTypeToJSON(value?: LocalizedCustomerType | null): any;
