"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function LocalizedCustomerStateFromJSON(json) {
    return LocalizedCustomerStateFromJSONTyped(json, false);
}
exports.LocalizedCustomerStateFromJSON = LocalizedCustomerStateFromJSON;
function LocalizedCustomerStateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'state': !runtime_1.exists(json, 'state') ? undefined : _1.CustomerStateFromJSON(json['state']),
        'localizedState': !runtime_1.exists(json, 'localizedState') ? undefined : json['localizedState'],
    };
}
exports.LocalizedCustomerStateFromJSONTyped = LocalizedCustomerStateFromJSONTyped;
function LocalizedCustomerStateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'state': _1.CustomerStateToJSON(value.state),
        'localizedState': value.localizedState,
    };
}
exports.LocalizedCustomerStateToJSON = LocalizedCustomerStateToJSON;
