/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerState } from './';
/**
 *
 * @export
 * @interface LocalizedCustomerState
 */
export interface LocalizedCustomerState {
    /**
     *
     * @type {CustomerState}
     * @memberof LocalizedCustomerState
     */
    state?: CustomerState;
    /**
     *
     * @type {string}
     * @memberof LocalizedCustomerState
     */
    localizedState?: string;
}
export declare function LocalizedCustomerStateFromJSON(json: any): LocalizedCustomerState;
export declare function LocalizedCustomerStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedCustomerState;
export declare function LocalizedCustomerStateToJSON(value?: LocalizedCustomerState | null): any;
