/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductAvailability } from './';
/**
 *
 * @export
 * @interface LocalizedProductAvailability
 */
export interface LocalizedProductAvailability {
    /**
     *
     * @type {ProductAvailability}
     * @memberof LocalizedProductAvailability
     */
    availability?: ProductAvailability;
    /**
     *
     * @type {string}
     * @memberof LocalizedProductAvailability
     */
    localizedAvailability?: string;
}
export declare function LocalizedProductAvailabilityFromJSON(json: any): LocalizedProductAvailability;
export declare function LocalizedProductAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedProductAvailability;
export declare function LocalizedProductAvailabilityToJSON(value?: LocalizedProductAvailability | null): any;
