"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function LocalizedBooleanValueFromJSON(json) {
    return LocalizedBooleanValueFromJSONTyped(json, false);
}
exports.LocalizedBooleanValueFromJSON = LocalizedBooleanValueFromJSON;
function LocalizedBooleanValueFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'value': !runtime_1.exists(json, 'value') ? undefined : _1.BooleanValueFromJSON(json['value']),
        'localizedValue': !runtime_1.exists(json, 'localizedValue') ? undefined : json['localizedValue'],
    };
}
exports.LocalizedBooleanValueFromJSONTyped = LocalizedBooleanValueFromJSONTyped;
function LocalizedBooleanValueToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'value': _1.BooleanValueToJSON(value.value),
        'localizedValue': value.localizedValue,
    };
}
exports.LocalizedBooleanValueToJSON = LocalizedBooleanValueToJSON;
