"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function LocalizedCustomerNativeStatusFromJSON(json) {
    return LocalizedCustomerNativeStatusFromJSONTyped(json, false);
}
exports.LocalizedCustomerNativeStatusFromJSON = LocalizedCustomerNativeStatusFromJSON;
function LocalizedCustomerNativeStatusFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'nativeStatus': !runtime_1.exists(json, 'nativeStatus') ? undefined : _1.CustomerNativeStatusFromJSON(json['nativeStatus']),
        'localizedNativeStatus': !runtime_1.exists(json, 'localizedNativeStatus') ? undefined : json['localizedNativeStatus'],
    };
}
exports.LocalizedCustomerNativeStatusFromJSONTyped = LocalizedCustomerNativeStatusFromJSONTyped;
function LocalizedCustomerNativeStatusToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'nativeStatus': _1.CustomerNativeStatusToJSON(value.nativeStatus),
        'localizedNativeStatus': value.localizedNativeStatus,
    };
}
exports.LocalizedCustomerNativeStatusToJSON = LocalizedCustomerNativeStatusToJSON;
