"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function LocalizedRejectionReasonFromJSON(json) {
    return LocalizedRejectionReasonFromJSONTyped(json, false);
}
exports.LocalizedRejectionReasonFromJSON = LocalizedRejectionReasonFromJSON;
function LocalizedRejectionReasonFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'rejectionReason': !runtime_1.exists(json, 'rejectionReason') ? undefined : _1.RejectionReasonFromJSON(json['rejectionReason']),
        'localizedRejectionReason': !runtime_1.exists(json, 'localizedRejectionReason') ? undefined : json['localizedRejectionReason'],
    };
}
exports.LocalizedRejectionReasonFromJSONTyped = LocalizedRejectionReasonFromJSONTyped;
function LocalizedRejectionReasonToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'rejectionReason': _1.RejectionReasonToJSON(value.rejectionReason),
        'localizedRejectionReason': value.localizedRejectionReason,
    };
}
exports.LocalizedRejectionReasonToJSON = LocalizedRejectionReasonToJSON;
