/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RejectionReason } from './';
/**
 *
 * @export
 * @interface LocalizedRejectionReason
 */
export interface LocalizedRejectionReason {
    /**
     *
     * @type {RejectionReason}
     * @memberof LocalizedRejectionReason
     */
    rejectionReason?: RejectionReason;
    /**
     *
     * @type {string}
     * @memberof LocalizedRejectionReason
     */
    localizedRejectionReason?: string;
}
export declare function LocalizedRejectionReasonFromJSON(json: any): LocalizedRejectionReason;
export declare function LocalizedRejectionReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedRejectionReason;
export declare function LocalizedRejectionReasonToJSON(value?: LocalizedRejectionReason | null): any;
