"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function LocalizedErrorCodeFromJSON(json) {
    return LocalizedErrorCodeFromJSONTyped(json, false);
}
exports.LocalizedErrorCodeFromJSON = LocalizedErrorCodeFromJSON;
function LocalizedErrorCodeFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'errorCode': !runtime_1.exists(json, 'errorCode') ? undefined : _1.ErrorCodeFromJSON(json['errorCode']),
        'localizedErrorCode': !runtime_1.exists(json, 'localizedErrorCode') ? undefined : json['localizedErrorCode'],
    };
}
exports.LocalizedErrorCodeFromJSONTyped = LocalizedErrorCodeFromJSONTyped;
function LocalizedErrorCodeToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'errorCode': _1.ErrorCodeToJSON(value.errorCode),
        'localizedErrorCode': value.localizedErrorCode,
    };
}
exports.LocalizedErrorCodeToJSON = LocalizedErrorCodeToJSON;
