/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorCode } from './';
/**
 *
 * @export
 * @interface LocalizedErrorCode
 */
export interface LocalizedErrorCode {
    /**
     *
     * @type {ErrorCode}
     * @memberof LocalizedErrorCode
     */
    errorCode?: ErrorCode;
    /**
     *
     * @type {string}
     * @memberof LocalizedErrorCode
     */
    localizedErrorCode?: string;
}
export declare function LocalizedErrorCodeFromJSON(json: any): LocalizedErrorCode;
export declare function LocalizedErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedErrorCode;
export declare function LocalizedErrorCodeToJSON(value?: LocalizedErrorCode | null): any;
