/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerNativeStatus } from './';
/**
 *
 * @export
 * @interface LocalizedCustomerNativeStatus
 */
export interface LocalizedCustomerNativeStatus {
    /**
     *
     * @type {CustomerNativeStatus}
     * @memberof LocalizedCustomerNativeStatus
     */
    nativeStatus?: CustomerNativeStatus;
    /**
     *
     * @type {string}
     * @memberof LocalizedCustomerNativeStatus
     */
    localizedNativeStatus?: string;
}
export declare function LocalizedCustomerNativeStatusFromJSON(json: any): LocalizedCustomerNativeStatus;
export declare function LocalizedCustomerNativeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedCustomerNativeStatus;
export declare function LocalizedCustomerNativeStatusToJSON(value?: LocalizedCustomerNativeStatus | null): any;
