"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function LocalizedProductAvailabilityFromJSON(json) {
    return LocalizedProductAvailabilityFromJSONTyped(json, false);
}
exports.LocalizedProductAvailabilityFromJSON = LocalizedProductAvailabilityFromJSON;
function LocalizedProductAvailabilityFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'availability': !runtime_1.exists(json, 'availability') ? undefined : _1.ProductAvailabilityFromJSON(json['availability']),
        'localizedAvailability': !runtime_1.exists(json, 'localizedAvailability') ? undefined : json['localizedAvailability'],
    };
}
exports.LocalizedProductAvailabilityFromJSONTyped = LocalizedProductAvailabilityFromJSONTyped;
function LocalizedProductAvailabilityToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'availability': _1.ProductAvailabilityToJSON(value.availability),
        'localizedAvailability': value.localizedAvailability,
    };
}
exports.LocalizedProductAvailabilityToJSON = LocalizedProductAvailabilityToJSON;
