/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum NullableBooleanValue {
    TRUE = "TRUE",
    FALSE = "FALSE"
}
export declare function NullableBooleanValueFromJSON(json: any): NullableBooleanValue;
export declare function NullableBooleanValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableBooleanValue;
export declare function NullableBooleanValueToJSON(value?: NullableBooleanValue | null): any;
