"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var NullableProductAvailability;
(function (NullableProductAvailability) {
    NullableProductAvailability["AVAILABLE"] = "AVAILABLE";
    NullableProductAvailability["NOTAVAILABLE"] = "NOT_AVAILABLE";
    NullableProductAvailability["SHORTTERMNOTAVAILABLE"] = "SHORT_TERM_NOT_AVAILABLE";
    NullableProductAvailability["MEDIUMTERMNOTAVAILABLE"] = "MEDIUM_TERM_NOT_AVAILABLE";
    NullableProductAvailability["LONGTERMNOTAVAILABLE"] = "LONG_TERM_NOT_AVAILABLE";
})(NullableProductAvailability = exports.NullableProductAvailability || (exports.NullableProductAvailability = {}));
function NullableProductAvailabilityFromJSON(json) {
    return NullableProductAvailabilityFromJSONTyped(json, false);
}
exports.NullableProductAvailabilityFromJSON = NullableProductAvailabilityFromJSON;
function NullableProductAvailabilityFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.NullableProductAvailabilityFromJSONTyped = NullableProductAvailabilityFromJSONTyped;
function NullableProductAvailabilityToJSON(value) {
    return value;
}
exports.NullableProductAvailabilityToJSON = NullableProductAvailabilityToJSON;
