/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum NullableProductAvailability {
    AVAILABLE = "AVAILABLE",
    NOTAVAILABLE = "NOT_AVAILABLE",
    SHORTTERMNOTAVAILABLE = "SHORT_TERM_NOT_AVAILABLE",
    MEDIUMTERMNOTAVAILABLE = "MEDIUM_TERM_NOT_AVAILABLE",
    LONGTERMNOTAVAILABLE = "LONG_TERM_NOT_AVAILABLE"
}
export declare function NullableProductAvailabilityFromJSON(json: any): NullableProductAvailability;
export declare function NullableProductAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableProductAvailability;
export declare function NullableProductAvailabilityToJSON(value?: NullableProductAvailability | null): any;
