/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
    /**
     *
     * @type {number}
     * @memberof PageInfo
     */
    pageNumber?: number;
    /**
     *
     * @type {number}
     * @memberof PageInfo
     */
    totalElements?: number;
    /**
     *
     * @type {number}
     * @memberof PageInfo
     */
    totalPages?: number;
}
export declare function PageInfoFromJSON(json: any): PageInfo;
export declare function PageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfo;
export declare function PageInfoToJSON(value?: PageInfo | null): any;
