"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function PageInfoFromJSON(json) {
    return PageInfoFromJSONTyped(json, false);
}
exports.PageInfoFromJSON = PageInfoFromJSON;
function PageInfoFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'pageNumber': !runtime_1.exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'totalElements': !runtime_1.exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !runtime_1.exists(json, 'totalPages') ? undefined : json['totalPages'],
    };
}
exports.PageInfoFromJSONTyped = PageInfoFromJSONTyped;
function PageInfoToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'pageNumber': value.pageNumber,
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
    };
}
exports.PageInfoToJSON = PageInfoToJSON;
