"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function ProductDetailsFromJSON(json) {
    return ProductDetailsFromJSONTyped(json, false);
}
exports.ProductDetailsFromJSON = ProductDetailsFromJSON;
function ProductDetailsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'isVisible': !runtime_1.exists(json, 'isVisible') ? undefined : _1.BooleanValueFromJSON(json['isVisible']),
        'availability': !runtime_1.exists(json, 'availability') ? undefined : _1.ProductAvailabilityFromJSON(json['availability']),
        'statusId': !runtime_1.exists(json, 'statusId') ? undefined : json['statusId'],
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'price': !runtime_1.exists(json, 'price') ? undefined : json['price'],
        'minimumOrderQuantity': !runtime_1.exists(json, 'minimumOrderQuantity') ? undefined : json['minimumOrderQuantity'],
        'maximumOrderQuantity': !runtime_1.exists(json, 'maximumOrderQuantity') ? undefined : json['maximumOrderQuantity'],
        'associatedProducts': !runtime_1.exists(json, 'associatedProducts') ? undefined : json['associatedProducts'],
        'imageFilename': !runtime_1.exists(json, 'imageFilename') ? undefined : json['imageFilename'],
        'imageFilepath': !runtime_1.exists(json, 'imageFilepath') ? undefined : json['imageFilepath'],
        'imageUploadDate': !runtime_1.exists(json, 'imageUploadDate') ? undefined : (new Date(json['imageUploadDate'])),
        'sourceSystem': !runtime_1.exists(json, 'sourceSystem') ? undefined : _1.SourceSystemFromJSON(json['sourceSystem']),
    };
}
exports.ProductDetailsFromJSONTyped = ProductDetailsFromJSONTyped;
function ProductDetailsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'isVisible': _1.BooleanValueToJSON(value.isVisible),
        'availability': _1.ProductAvailabilityToJSON(value.availability),
        'statusId': value.statusId,
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'minimumOrderQuantity': value.minimumOrderQuantity,
        'maximumOrderQuantity': value.maximumOrderQuantity,
        'associatedProducts': value.associatedProducts,
        'imageFilename': value.imageFilename,
        'imageFilepath': value.imageFilepath,
        'imageUploadDate': value.imageUploadDate === undefined ? undefined : (value.imageUploadDate.toISOString()),
        'sourceSystem': _1.SourceSystemToJSON(value.sourceSystem),
    };
}
exports.ProductDetailsToJSON = ProductDetailsToJSON;
