/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDetails } from './';
/**
 *
 * @export
 * @interface ProductDetailsResponse
 */
export interface ProductDetailsResponse {
    /**
     *
     * @type {ProductDetails}
     * @memberof ProductDetailsResponse
     */
    product?: ProductDetails;
}
export declare function ProductDetailsResponseFromJSON(json: any): ProductDetailsResponse;
export declare function ProductDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDetailsResponse;
export declare function ProductDetailsResponseToJSON(value?: ProductDetailsResponse | null): any;
