"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function ProductsResponseFromJSON(json) {
    return ProductsResponseFromJSONTyped(json, false);
}
exports.ProductsResponseFromJSON = ProductsResponseFromJSON;
function ProductsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'pageInfo': !runtime_1.exists(json, 'pageInfo') ? undefined : _1.PageInfoFromJSON(json['pageInfo']),
        'products': !runtime_1.exists(json, 'products') ? undefined : (json['products'].map(_1.ProductFromJSON)),
    };
}
exports.ProductsResponseFromJSONTyped = ProductsResponseFromJSONTyped;
function ProductsResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'pageInfo': _1.PageInfoToJSON(value.pageInfo),
        'products': value.products === undefined ? undefined : (value.products.map(_1.ProductToJSON)),
    };
}
exports.ProductsResponseToJSON = ProductsResponseToJSON;
