/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BooleanValue, ProductAvailability, SourceSystem } from './';
/**
 *
 * @export
 * @interface ProductDetails
 */
export interface ProductDetails {
    /**
     *
     * @type {string}
     * @memberof ProductDetails
     */
    id?: string;
    /**
     *
     * @type {BooleanValue}
     * @memberof ProductDetails
     */
    isVisible?: BooleanValue;
    /**
     *
     * @type {ProductAvailability}
     * @memberof ProductDetails
     */
    availability?: ProductAvailability;
    /**
     *
     * @type {string}
     * @memberof ProductDetails
     */
    statusId?: string;
    /**
     *
     * @type {string}
     * @memberof ProductDetails
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof ProductDetails
     */
    description?: string;
    /**
     *
     * @type {number}
     * @memberof ProductDetails
     */
    price?: number;
    /**
     *
     * @type {number}
     * @memberof ProductDetails
     */
    minimumOrderQuantity?: number;
    /**
     *
     * @type {number}
     * @memberof ProductDetails
     */
    maximumOrderQuantity?: number;
    /**
     *
     * @type {string}
     * @memberof ProductDetails
     */
    associatedProducts?: string;
    /**
     *
     * @type {string}
     * @memberof ProductDetails
     */
    imageFilename?: string;
    /**
     *
     * @type {string}
     * @memberof ProductDetails
     */
    imageFilepath?: string;
    /**
     *
     * @type {Date}
     * @memberof ProductDetails
     */
    imageUploadDate?: Date;
    /**
     *
     * @type {SourceSystem}
     * @memberof ProductDetails
     */
    sourceSystem?: SourceSystem;
}
export declare function ProductDetailsFromJSON(json: any): ProductDetails;
export declare function ProductDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDetails;
export declare function ProductDetailsToJSON(value?: ProductDetails | null): any;
