"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function ProductPartialFromJSON(json) {
    return ProductPartialFromJSONTyped(json, false);
}
exports.ProductPartialFromJSON = ProductPartialFromJSON;
function ProductPartialFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'isVisible': !runtime_1.exists(json, 'isVisible') ? undefined : _1.NullableBooleanValueFromJSON(json['isVisible']),
        'availability': !runtime_1.exists(json, 'availability') ? undefined : _1.NullableProductAvailabilityFromJSON(json['availability']),
        'minimumOrderQuantity': !runtime_1.exists(json, 'minimumOrderQuantity') ? undefined : json['minimumOrderQuantity'],
        'maximumOrderQuantity': !runtime_1.exists(json, 'maximumOrderQuantity') ? undefined : json['maximumOrderQuantity'],
        'associatedProducts': !runtime_1.exists(json, 'associatedProducts') ? undefined : json['associatedProducts'],
        'image': !runtime_1.exists(json, 'image') ? undefined : json['image'],
        'imageFilename': !runtime_1.exists(json, 'imageFilename') ? undefined : json['imageFilename'],
    };
}
exports.ProductPartialFromJSONTyped = ProductPartialFromJSONTyped;
function ProductPartialToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'isVisible': _1.NullableBooleanValueToJSON(value.isVisible),
        'availability': _1.NullableProductAvailabilityToJSON(value.availability),
        'minimumOrderQuantity': value.minimumOrderQuantity,
        'maximumOrderQuantity': value.maximumOrderQuantity,
        'associatedProducts': value.associatedProducts,
        'image': value.image,
        'imageFilename': value.imageFilename,
    };
}
exports.ProductPartialToJSON = ProductPartialToJSON;
