/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BooleanValue, ProductAvailability, SourceSystem } from './';
/**
 *
 * @export
 * @interface Product
 */
export interface Product {
    /**
     *
     * @type {string}
     * @memberof Product
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    statusId?: string;
    /**
     *
     * @type {BooleanValue}
     * @memberof Product
     */
    isVisible?: BooleanValue;
    /**
     *
     * @type {ProductAvailability}
     * @memberof Product
     */
    availability?: ProductAvailability;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    description?: string;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    minimumOrderQuantity?: number;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    maximumOrderQuantity?: number;
    /**
     *
     * @type {BooleanValue}
     * @memberof Product
     */
    hasMedia?: BooleanValue;
    /**
     *
     * @type {SourceSystem}
     * @memberof Product
     */
    sourceSystem?: SourceSystem;
}
export declare function ProductFromJSON(json: any): Product;
export declare function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product;
export declare function ProductToJSON(value?: Product | null): any;
