/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductPartial } from './';
/**
 *
 * @export
 * @interface ProductPartialRequest
 */
export interface ProductPartialRequest {
    /**
     *
     * @type {ProductPartial}
     * @memberof ProductPartialRequest
     */
    productPartial: ProductPartial;
}
export declare function ProductPartialRequestFromJSON(json: any): ProductPartialRequest;
export declare function ProductPartialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPartialRequest;
export declare function ProductPartialRequestToJSON(value?: ProductPartialRequest | null): any;
