"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function ProductFromJSON(json) {
    return ProductFromJSONTyped(json, false);
}
exports.ProductFromJSON = ProductFromJSON;
function ProductFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'statusId': !runtime_1.exists(json, 'statusId') ? undefined : json['statusId'],
        'isVisible': !runtime_1.exists(json, 'isVisible') ? undefined : _1.BooleanValueFromJSON(json['isVisible']),
        'availability': !runtime_1.exists(json, 'availability') ? undefined : _1.ProductAvailabilityFromJSON(json['availability']),
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'minimumOrderQuantity': !runtime_1.exists(json, 'minimumOrderQuantity') ? undefined : json['minimumOrderQuantity'],
        'maximumOrderQuantity': !runtime_1.exists(json, 'maximumOrderQuantity') ? undefined : json['maximumOrderQuantity'],
        'hasMedia': !runtime_1.exists(json, 'hasMedia') ? undefined : _1.BooleanValueFromJSON(json['hasMedia']),
        'sourceSystem': !runtime_1.exists(json, 'sourceSystem') ? undefined : _1.SourceSystemFromJSON(json['sourceSystem']),
    };
}
exports.ProductFromJSONTyped = ProductFromJSONTyped;
function ProductToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'statusId': value.statusId,
        'isVisible': _1.BooleanValueToJSON(value.isVisible),
        'availability': _1.ProductAvailabilityToJSON(value.availability),
        'description': value.description,
        'minimumOrderQuantity': value.minimumOrderQuantity,
        'maximumOrderQuantity': value.maximumOrderQuantity,
        'hasMedia': _1.BooleanValueToJSON(value.hasMedia),
        'sourceSystem': _1.SourceSystemToJSON(value.sourceSystem),
    };
}
exports.ProductToJSON = ProductToJSON;
