/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum RejectionReason {
    ADDRESS = "ADDRESS",
    NAME = "NAME",
    OTHER = "OTHER",
    REFERENCE = "REFERENCE"
}
export declare function RejectionReasonFromJSON(json: any): RejectionReason;
export declare function RejectionReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectionReason;
export declare function RejectionReasonToJSON(value?: RejectionReason | null): any;
