"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var SearchCustomersByField;
(function (SearchCustomersByField) {
    SearchCustomersByField["NATIVESTATUS"] = "NATIVE_STATUS";
    SearchCustomersByField["ERPID"] = "ERP_ID";
    SearchCustomersByField["COMPANYNAME"] = "COMPANY_NAME";
    SearchCustomersByField["ADDRESS"] = "ADDRESS";
    SearchCustomersByField["STATE"] = "STATE";
    SearchCustomersByField["TYPE"] = "TYPE";
    SearchCustomersByField["NATIVECREATEDDATE"] = "NATIVE_CREATED_DATE";
    SearchCustomersByField["SOURCE"] = "SOURCE";
    SearchCustomersByField["REJECTIONREASON"] = "REJECTION_REASON";
})(SearchCustomersByField = exports.SearchCustomersByField || (exports.SearchCustomersByField = {}));
function SearchCustomersByFieldFromJSON(json) {
    return SearchCustomersByFieldFromJSONTyped(json, false);
}
exports.SearchCustomersByFieldFromJSON = SearchCustomersByFieldFromJSON;
function SearchCustomersByFieldFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.SearchCustomersByFieldFromJSONTyped = SearchCustomersByFieldFromJSONTyped;
function SearchCustomersByFieldToJSON(value) {
    return value;
}
exports.SearchCustomersByFieldToJSON = SearchCustomersByFieldToJSON;
