/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchByOperation, SearchCustomersByField } from './';
/**
 *
 * @export
 * @interface SearchCustomersBy
 */
export interface SearchCustomersBy {
    /**
     *
     * @type {SearchCustomersByField}
     * @memberof SearchCustomersBy
     */
    field?: SearchCustomersByField;
    /**
     *
     * @type {SearchByOperation}
     * @memberof SearchCustomersBy
     */
    operation?: SearchByOperation;
    /**
     *
     * @type {Array<string>}
     * @memberof SearchCustomersBy
     */
    values?: Array<string>;
}
export declare function SearchCustomersByFromJSON(json: any): SearchCustomersBy;
export declare function SearchCustomersByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCustomersBy;
export declare function SearchCustomersByToJSON(value?: SearchCustomersBy | null): any;
