/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum SearchAuditsByField {
    DATASET = "DATA_SET",
    HEADER = "HEADER",
    MESSAGE = "MESSAGE",
    INITIATOR = "INITIATOR",
    DATE = "DATE"
}
export declare function SearchAuditsByFieldFromJSON(json: any): SearchAuditsByField;
export declare function SearchAuditsByFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAuditsByField;
export declare function SearchAuditsByFieldToJSON(value?: SearchAuditsByField | null): any;
