"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var SearchAuditsByField;
(function (SearchAuditsByField) {
    SearchAuditsByField["DATASET"] = "DATA_SET";
    SearchAuditsByField["HEADER"] = "HEADER";
    SearchAuditsByField["MESSAGE"] = "MESSAGE";
    SearchAuditsByField["INITIATOR"] = "INITIATOR";
    SearchAuditsByField["DATE"] = "DATE";
})(SearchAuditsByField = exports.SearchAuditsByField || (exports.SearchAuditsByField = {}));
function SearchAuditsByFieldFromJSON(json) {
    return SearchAuditsByFieldFromJSONTyped(json, false);
}
exports.SearchAuditsByFieldFromJSON = SearchAuditsByFieldFromJSON;
function SearchAuditsByFieldFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.SearchAuditsByFieldFromJSONTyped = SearchAuditsByFieldFromJSONTyped;
function SearchAuditsByFieldToJSON(value) {
    return value;
}
exports.SearchAuditsByFieldToJSON = SearchAuditsByFieldToJSON;
