"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function SearchCustomersByFromJSON(json) {
    return SearchCustomersByFromJSONTyped(json, false);
}
exports.SearchCustomersByFromJSON = SearchCustomersByFromJSON;
function SearchCustomersByFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'field': !runtime_1.exists(json, 'field') ? undefined : _1.SearchCustomersByFieldFromJSON(json['field']),
        'operation': !runtime_1.exists(json, 'operation') ? undefined : _1.SearchByOperationFromJSON(json['operation']),
        'values': !runtime_1.exists(json, 'values') ? undefined : json['values'],
    };
}
exports.SearchCustomersByFromJSONTyped = SearchCustomersByFromJSONTyped;
function SearchCustomersByToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'field': _1.SearchCustomersByFieldToJSON(value.field),
        'operation': _1.SearchByOperationToJSON(value.operation),
        'values': value.values,
    };
}
exports.SearchCustomersByToJSON = SearchCustomersByToJSON;
