/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum SortAuditsBy {
    DATASET = "DATA_SET",
    HEADER = "HEADER",
    MESSAGE = "MESSAGE",
    INITIATOR = "INITIATOR",
    DATE = "DATE"
}
export declare function SortAuditsByFromJSON(json: any): SortAuditsBy;
export declare function SortAuditsByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortAuditsBy;
export declare function SortAuditsByToJSON(value?: SortAuditsBy | null): any;
