"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var SortDirection;
(function (SortDirection) {
    SortDirection["ASC"] = "ASC";
    SortDirection["DESC"] = "DESC";
})(SortDirection = exports.SortDirection || (exports.SortDirection = {}));
function SortDirectionFromJSON(json) {
    return SortDirectionFromJSONTyped(json, false);
}
exports.SortDirectionFromJSON = SortDirectionFromJSON;
function SortDirectionFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.SortDirectionFromJSONTyped = SortDirectionFromJSONTyped;
function SortDirectionToJSON(value) {
    return value;
}
exports.SortDirectionToJSON = SortDirectionToJSON;
