"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var SortCustomersBy;
(function (SortCustomersBy) {
    SortCustomersBy["NATIVESTATUS"] = "NATIVE_STATUS";
    SortCustomersBy["ERPID"] = "ERP_ID";
    SortCustomersBy["COMPANYNAME"] = "COMPANY_NAME";
    SortCustomersBy["ADDRESS"] = "ADDRESS";
    SortCustomersBy["STATE"] = "STATE";
    SortCustomersBy["TYPE"] = "TYPE";
    SortCustomersBy["NATIVECREATEDDATE"] = "NATIVE_CREATED_DATE";
    SortCustomersBy["SOURCE"] = "SOURCE";
    SortCustomersBy["REJECTIONREASON"] = "REJECTION_REASON";
})(SortCustomersBy = exports.SortCustomersBy || (exports.SortCustomersBy = {}));
function SortCustomersByFromJSON(json) {
    return SortCustomersByFromJSONTyped(json, false);
}
exports.SortCustomersByFromJSON = SortCustomersByFromJSON;
function SortCustomersByFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.SortCustomersByFromJSONTyped = SortCustomersByFromJSONTyped;
function SortCustomersByToJSON(value) {
    return value;
}
exports.SortCustomersByToJSON = SortCustomersByToJSON;
