"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *
 * @export
 * @enum {string}
 */
var SortProductsBy;
(function (SortProductsBy) {
    SortProductsBy["ISVISIBLE"] = "IS_VISIBLE";
    SortProductsBy["AVAILABILITY"] = "AVAILABILITY";
    SortProductsBy["PRODUCTID"] = "PRODUCT_ID";
    SortProductsBy["DESCRIPTION"] = "DESCRIPTION";
    SortProductsBy["MINIMUMORDERQUANTITY"] = "MINIMUM_ORDER_QUANTITY";
    SortProductsBy["MAXIMUMORDERQUANTITY"] = "MAXIMUM_ORDER_QUANTITY";
    SortProductsBy["HASMEDIA"] = "HAS_MEDIA";
    SortProductsBy["SOURCE"] = "SOURCE";
})(SortProductsBy = exports.SortProductsBy || (exports.SortProductsBy = {}));
function SortProductsByFromJSON(json) {
    return SortProductsByFromJSONTyped(json, false);
}
exports.SortProductsByFromJSON = SortProductsByFromJSON;
function SortProductsByFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.SortProductsByFromJSONTyped = SortProductsByFromJSONTyped;
function SortProductsByToJSON(value) {
    return value;
}
exports.SortProductsByToJSON = SortProductsByToJSON;
