/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum SortProductsBy {
    ISVISIBLE = "IS_VISIBLE",
    AVAILABILITY = "AVAILABILITY",
    PRODUCTID = "PRODUCT_ID",
    DESCRIPTION = "DESCRIPTION",
    MINIMUMORDERQUANTITY = "MINIMUM_ORDER_QUANTITY",
    MAXIMUMORDERQUANTITY = "MAXIMUM_ORDER_QUANTITY",
    HASMEDIA = "HAS_MEDIA",
    SOURCE = "SOURCE"
}
export declare function SortProductsByFromJSON(json: any): SortProductsBy;
export declare function SortProductsByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortProductsBy;
export declare function SortProductsByToJSON(value?: SortProductsBy | null): any;
