/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum SortDirection {
    ASC = "ASC",
    DESC = "DESC"
}
export declare function SortDirectionFromJSON(json: any): SortDirection;
export declare function SortDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortDirection;
export declare function SortDirectionToJSON(value?: SortDirection | null): any;
