/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SourceSystem
 */
export interface SourceSystem {
    /**
     *
     * @type {string}
     * @memberof SourceSystem
     */
    name: string;
}
export declare function SourceSystemFromJSON(json: any): SourceSystem;
export declare function SourceSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceSystem;
export declare function SourceSystemToJSON(value?: SourceSystem | null): any;
