"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function SourceSystemsResponseFromJSON(json) {
    return SourceSystemsResponseFromJSONTyped(json, false);
}
exports.SourceSystemsResponseFromJSON = SourceSystemsResponseFromJSON;
function SourceSystemsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'sourceSystems': !runtime_1.exists(json, 'sourceSystems') ? undefined : (json['sourceSystems'].map(_1.SourceSystemFromJSON)),
    };
}
exports.SourceSystemsResponseFromJSONTyped = SourceSystemsResponseFromJSONTyped;
function SourceSystemsResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'sourceSystems': value.sourceSystems === undefined ? undefined : (value.sourceSystems.map(_1.SourceSystemToJSON)),
    };
}
exports.SourceSystemsResponseToJSON = SourceSystemsResponseToJSON;
