export const CUSTOMER_DETAILS_LABELS = {
  CITY: 'Stadt',
  COMPANY_NAME: 'Praxisname',
  COUNTRY_CODE: 'Länderkennzeichen',
  ERP_ID: 'Zoetis Kd.-Nr.',
  FIRST_NAME: 'Vorname',
  FREE_TEXT: 'Freitext',
  LAST_NAME: 'Name',
  NATIVE_CREATED_DATE: 'Datum Übermittlung',
  NATIVE_ID: 'eComm Kd.-Nr.',
  NATIVE_STATUS: 'Status',
  POSTAL_CODE: 'PLZ',
  REJECTION_REASON: 'Kommentar',
  SOURCE_SYSTEM: 'Plattform',
  STATE: 'Kundenstatus',
  STREET_ADDRESS: 'Straße/Nr.',
  TITLE: 'Titel',
  TYPE: 'Abgabe/Praxis.',
}
