/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { AuditsRequest, AuditsResponse } from '../models';
export interface GetAuditsRequest {
    auditsRequest: AuditsRequest;
}
/**
 * AuditApi - interface
 *
 * @export
 * @interface AuditApiInterface
 */
export interface AuditApiInterface {
    /**
     *
     * @summary Audit list
     * @param {AuditsRequest} auditsRequest Get audits request parameters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApiInterface
     */
    getAuditsRaw(requestParameters: GetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>>;
    /**
     * Audit list
     */
    getAudits(requestParameters: GetAuditsRequest): Promise<AuditsResponse>;
}
/**
 *
 */
export declare class AuditApi extends runtime.BaseAPI implements AuditApiInterface {
    /**
     * Audit list
     */
    getAuditsRaw(requestParameters: GetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>>;
    /**
     * Audit list
     */
    getAudits(requestParameters: GetAuditsRequest): Promise<AuditsResponse>;
}
