/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { AuditsRequest, AuditsResponse } from '../models';
export interface NgetAuditsRequest {
    auditsRequest: AuditsRequest;
}
/**
 * CauditsApi - interface
 *
 * @export
 * @interface CauditsApiInterface
 */
export interface CauditsApiInterface {
    /**
     *
     * @summary Audit list
     * @param {AuditsRequest} auditsRequest Get audits request parameters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CauditsApiInterface
     */
    ngetAuditsRaw(requestParameters: NgetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>>;
    /**
     * Audit list
     */
    ngetAudits(requestParameters: NgetAuditsRequest): Promise<AuditsResponse>;
}
/**
 *
 */
export declare class CauditsApi extends runtime.BaseAPI implements CauditsApiInterface {
    /**
     * Audit list
     */
    ngetAuditsRaw(requestParameters: NgetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>>;
    /**
     * Audit list
     */
    ngetAudits(requestParameters: NgetAuditsRequest): Promise<AuditsResponse>;
}
