/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { CustomerLookupResponse } from '../models';
export interface GetCustomerLookupRequest {
    id: string;
}
/**
 * CustomerLookupApi - interface
 *
 * @export
 * @interface CustomerLookupApiInterface
 */
export interface CustomerLookupApiInterface {
    /**
     *
     * @summary Customer lookup
     * @param {string} id Customer ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomerLookupApiInterface
     */
    getCustomerLookupRaw(requestParameters: GetCustomerLookupRequest): Promise<runtime.ApiResponse<CustomerLookupResponse>>;
    /**
     * Customer lookup
     */
    getCustomerLookup(requestParameters: GetCustomerLookupRequest): Promise<CustomerLookupResponse>;
}
/**
 *
 */
export declare class CustomerLookupApi extends runtime.BaseAPI implements CustomerLookupApiInterface {
    /**
     * Customer lookup
     */
    getCustomerLookupRaw(requestParameters: GetCustomerLookupRequest): Promise<runtime.ApiResponse<CustomerLookupResponse>>;
    /**
     * Customer lookup
     */
    getCustomerLookup(requestParameters: GetCustomerLookupRequest): Promise<CustomerLookupResponse>;
}
