/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { ProductDetailsResponse, ProductPartialRequest, ProductsRequest, ProductsResponse } from '../models';
export interface GetProductDetailsRequest {
    id: string;
    statusId: string;
}
export interface GetProductsRequest {
    productsRequest: ProductsRequest;
}
export interface UpdateProductRequest {
    id: string;
    statusId: string;
    productPartialRequest: ProductPartialRequest;
    applyForAllSystems?: boolean;
}
/**
 * ProductApi - interface
 *
 * @export
 * @interface ProductApiInterface
 */
export interface ProductApiInterface {
    /**
     *
     * @summary Product details
     * @param {string} id product ID
     * @param {string} statusId product status ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    getProductDetailsRaw(requestParameters: GetProductDetailsRequest): Promise<runtime.ApiResponse<ProductDetailsResponse>>;
    /**
     * Product details
     */
    getProductDetails(requestParameters: GetProductDetailsRequest): Promise<ProductDetailsResponse>;
    /**
     *
     * @summary Products list
     * @param {ProductsRequest} productsRequest Get products request parameters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    getProductsRaw(requestParameters: GetProductsRequest): Promise<runtime.ApiResponse<ProductsResponse>>;
    /**
     * Products list
     */
    getProducts(requestParameters: GetProductsRequest): Promise<ProductsResponse>;
    /**
     *
     * @summary Product details update
     * @param {string} id Customer ID
     * @param {string} statusId Product status context
     * @param {ProductPartialRequest} productPartialRequest Updated product
     * @param {boolean} [applyForAllSystems] Tells if apply changes to all systems in product context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    updateProductRaw(requestParameters: UpdateProductRequest): Promise<runtime.ApiResponse<void>>;
    /**
     * Product details update
     */
    updateProduct(requestParameters: UpdateProductRequest): Promise<void>;
}
/**
 *
 */
export declare class ProductApi extends runtime.BaseAPI implements ProductApiInterface {
    /**
     * Product details
     */
    getProductDetailsRaw(requestParameters: GetProductDetailsRequest): Promise<runtime.ApiResponse<ProductDetailsResponse>>;
    /**
     * Product details
     */
    getProductDetails(requestParameters: GetProductDetailsRequest): Promise<ProductDetailsResponse>;
    /**
     * Products list
     */
    getProductsRaw(requestParameters: GetProductsRequest): Promise<runtime.ApiResponse<ProductsResponse>>;
    /**
     * Products list
     */
    getProducts(requestParameters: GetProductsRequest): Promise<ProductsResponse>;
    /**
     * Product details update
     */
    updateProductRaw(requestParameters: UpdateProductRequest): Promise<runtime.ApiResponse<void>>;
    /**
     * Product details update
     */
    updateProduct(requestParameters: UpdateProductRequest): Promise<void>;
}
