/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SourceSystemsResponse } from '../models';
/**
 * SourceSystemApi - interface
 *
 * @export
 * @interface SourceSystemApiInterface
 */
export interface SourceSystemApiInterface {
    /**
     *
     * @summary Source system list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceSystemApiInterface
     */
    getSourceSystemsRaw(): Promise<runtime.ApiResponse<SourceSystemsResponse>>;
    /**
     * Source system list
     */
    getSourceSystems(): Promise<SourceSystemsResponse>;
}
/**
 *
 */
export declare class SourceSystemApi extends runtime.BaseAPI implements SourceSystemApiInterface {
    /**
     * Source system list
     */
    getSourceSystemsRaw(): Promise<runtime.ApiResponse<SourceSystemsResponse>>;
    /**
     * Source system list
     */
    getSourceSystems(): Promise<SourceSystemsResponse>;
}
