/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { AuthenticatedUserResponse } from '../models';
/**
 * UserApi - interface
 *
 * @export
 * @interface UserApiInterface
 */
export interface UserApiInterface {
    /**
     *
     * @summary Authenticated user details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    getAuthenticatedUserRaw(): Promise<runtime.ApiResponse<AuthenticatedUserResponse>>;
    /**
     * Authenticated user details
     */
    getAuthenticatedUser(): Promise<AuthenticatedUserResponse>;
}
/**
 *
 */
export declare class UserApi extends runtime.BaseAPI implements UserApiInterface {
    /**
     * Authenticated user details
     */
    getAuthenticatedUserRaw(): Promise<runtime.ApiResponse<AuthenticatedUserResponse>>;
    /**
     * Authenticated user details
     */
    getAuthenticatedUser(): Promise<AuthenticatedUserResponse>;
}
